### ISSUE TITLE
【功能建议】希望能够加入 添加和删除本地通知的接口。

### ISSUE THREAD

**Issue by fenglu09** [GetuiLaboratory/react-native-getui#10]
RT。
希望能够新增 加入 添加本地通知和清除本地通知的功能。
我们使用的是透传消息，收到消息后，当app在后台时，希望能够添加一条本地通知。并且可以捕获点击事件。
如果`react-native-getui`能够自带这些功能，就免去了寻找其他库的时间了，使用更便捷

**Comment by GetuiLab** [comment]
你好，麻烦加下官网首页技术支持的qq，在讨论组里沟通！！



support@getui.com
 
发件人： fenglu09
发送时间： 2017-11-21 21:06
收件人： GetuiLaboratory/react-native-getui
抄送： Subscribed
主题： [GetuiLaboratory/react-native-getui] 【功能建议】希望能够加入 添加和删除本地通知的接口。 (#10)
RT。
希望能够新增 加入 添加本地通知和清除本地通知的功能。
我们使用的是透传消息，收到消息后，当app在后台时，希望能够添加一条本地通知。并且可以捕获点击事件。
如果react-native-getui能够自带这些功能，就免去了寻找其他库的时间了，使用更便捷
