### ISSUE TITLE
Android 应用被杀死后，再次打开，无法收到被杀死期间的消息

### ISSUE THREAD

**Issue by fenglu09** [GetuiLaboratory/react-native-getui#11]
APP被系统kill掉后，在这段时间内推送给app消息，再次启动app时，无法收到这些消息。

**Comment by GetuiLab** [comment]
您好，推送的时候有设置过离线消息吗，在离线时间内cid在线，离线消息才会下发，如果还有疑问，麻烦加下官网首页技术支持的qq！！



support@getui.com
 
发件人： fenglu09
发送时间： 2017-11-22 14:36
收件人： GetuiLaboratory/react-native-getui
抄送： Subscribed
主题： [GetuiLaboratory/react-native-getui] Android 应用被杀死后，再次打开，无法收到被杀死期间的消息 (#11)
APP被系统kill掉后，在这段时间内推送给app消息，再次启动app时，无法收到这些消息。

**Comment by fenglu09** [comment]
加过你们的QQ，有一个讨论组， 现在没人响应。 我设置过离线时间为三天

**Comment by fenglu09** [comment]
而且被杀死后，，从个推的管理后台推送透传消息，设置有效时长是2小时，再次启动也是收不到消息。

**Comment by GetuiLab** [comment]
麻烦再说句话，因为我们讨论组比较多，有时候可能被覆盖了，邮件交流不太方便！



support@getui.com
 
发件人： fenglu09
发送时间： 2017-11-22 14:43
收件人： GetuiLaboratory/react-native-getui
抄送： GetuiLab; Comment
主题： Re: [GetuiLaboratory/react-native-getui] Android 应用被杀死后，再次打开，无法收到被杀死期间的消息 (#11)
加过你们的QQ，有一个讨论组， 现在没人响应。 我设置过离线时间为三天

**Comment by GetuiLab** [comment]
讨论组沟通好吗，谢谢配合！



support@getui.com
 
发件人： fenglu09
发送时间： 2017-11-22 14:56
收件人： GetuiLaboratory/react-native-getui
抄送： GetuiLab; Comment
主题： Re: [GetuiLaboratory/react-native-getui] Android 应用被杀死后，再次打开，无法收到被杀死期间的消息 (#11)
而且被杀死后，，从个推的管理后台推送透传消息，设置有效时长是2小时，再次启动也是收不到消息。
