### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by zzdjk6** [GetuiLaboratory/react-native-getui#12]
:react-native-getui:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-getui:processReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by zzdjk6** [comment]
PR在 #13

**Comment by GetuiLab** [comment]
有什么问题，麻烦加官网首页技术支持的qq！！



support@getui.com
 
发件人： Shenghan Chen
发送时间： 2018-01-05 18:20
收件人： GetuiLaboratory/react-native-getui
抄送： Subscribed
主题： [GetuiLaboratory/react-native-getui] 编译失败 (#12)
:react-native-getui:processReleaseResources FAILED
FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task ':react-native-getui:processReleaseResources'.
com.android.ide.common.process.ProcessException: Failed to execute aapt
Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED

**Comment by zjjne** [comment]
麻烦将修复的代码更新到npm

**Comment by GetuiLab** [comment]
您好，有什么问题，麻烦您加下官网首页技术支持的qq！！


support@getui.com
 
发件人： zjjne
发送时间： 2018-01-25 18:15
收件人： GetuiLaboratory/react-native-getui
抄送： GetuiLab; Comment
主题： Re: [GetuiLaboratory/react-native-getui] 编译失败 (#12)
麻烦将修复的代码更新到npm
