### ISSUE TITLE
iOS平台杀了应用进程，从通知中心的消息点进应用无法接收到apns消息

### ISSUE THREAD

**Issue by leechan** [GetuiLaboratory/react-native-getui#14]
杀了进程，从通知中心的消息点进应用不会触发receiveRemoteNotification事件，所以就没办法做相应的跳转处理。麻烦看看这个问题，非常感谢。

**Comment by GetuiLab** [comment]
麻烦您加下官网首页技术支持的qq，具体沟通一下！！



support@getui.com
 
发件人： leechan
发送时间： 2018-03-08 19:46
收件人： GetuiLaboratory/react-native-getui
抄送： Subscribed
主题： [GetuiLaboratory/react-native-getui] iOS平台杀了应用进程，从通知中心的消息点进应用无法接收到apns消息 (#14)
杀了进程，从通知中心的消息点进应用不会触发receiveRemoteNotification事件，所以就没办法做相应的跳转处理。麻烦看看这个问题，非常感谢。
―

**Comment by lin493369** [comment]
新版已解决。

**Comment by GetuiLab** [comment]
您好，麻烦加下官网首页技术支持的qq：2880983154，qq里沟通！


support@getui.com
 
发件人： 小袋子
发送时间： 2018-03-19 10:49
收件人： GetuiLaboratory/react-native-getui
抄送： GetuiLab; Comment
主题： Re: [GetuiLaboratory/react-native-getui] iOS平台杀了应用进程，从通知中心的消息点进应用无法接收到apns消息 (#14)
Closed #14.

**Comment by GetuiLab** [comment]
您好，麻烦加下官网首页技术支持的qq，在qq沟通您具体的问题！！



support@getui.com
 
发件人： 小袋子
发送时间： 2018-03-19 10:49
收件人： GetuiLaboratory/react-native-getui
抄送： GetuiLab; Comment
主题： Re: [GetuiLaboratory/react-native-getui] iOS平台杀了应用进程，从通知中心的消息点进应用无法接收到apns消息 (#14)
新版已解决。

**Comment by leechan** [comment]
我已经更新到了这个版本，但是发现该问题还是存在，麻烦确认下是否已经修复，非常感谢。
