### ISSUE TITLE
demo中读取Cid为null,不能使用

### ISSUE THREAD

**Issue by chenxiong666** [GetuiLaboratory/react-native-getui#16]

**Comment by GetuiLab** [comment]
您好，麻烦加下官网首页技术支持的qq沟通下具体的问题!!



support@getui.com
 
发件人： chenxiong666
发送时间： 2018-04-27 16:53
收件人： GetuiLaboratory/react-native-getui
抄送： Subscribed
主题： [GetuiLaboratory/react-native-getui] demo中读取Cid为null,不能使用 (#16)

**Comment by tomorrowNicest** [comment]
大佬，能获取cid了嘛？

**Comment by Ezreal-lup** [comment]
您好，麻烦加官网首页技术支持的qq，详细了解问题后协助解决
