### ISSUE TITLE
目标版本过低,V4依赖版本需要

### ISSUE THREAD

**Issue by tututututututu** [GetuiLaboratory/react-native-getui#17]
编译失败
Error:In <declare-styleable> FontFamilyFont, unable to find attribute android:font
Error:In <declare-styleable> FontFamilyFont, unable to find attribute android:fontVariationSettings
Error:In <declare-styleable> FontFamilyFont, unable to find attribute android:ttcIndex

原因是Android中的build.gradle依赖的compile 'com.android.support:support-v4:+'没有指定具体版本
另外        targetSdkVersion 22这个版本太低了,希望能修改这两个问题

**Comment by monkeydbobo** [comment]
谢谢建议

**Comment by GetuiLab** [comment]
您好：
  针对您反馈的问题，可加官网技术支持QQ 具体沟通协助您排查解决。



support@getui.com
 
发件人： tutu
发送时间： 2018-05-21 15:15
收件人： GetuiLaboratory/react-native-getui
抄送： Subscribed
主题： Re: [GetuiLaboratory/react-native-getui] 目标版本过低,V4依赖版本需要 (#17)
hi 目前还是没有 修改,请问有什么考虑吗

**Comment by monkeydbobo** [comment]
你是改到什么版本的

**Comment by tututututututu** [comment]
越新越好 我改到了26

**Comment by monkeydbobo** [comment]
compile 'com.android.support:support-v4:25+' 把官网的改到这个版本，我这边用没有什么问题了。

**Comment by tututututututu** [comment]
最新的1.1.22  依然是compile 'com.android.support:support-v4:+'   并不是25+

**Comment by monkeydbobo** [comment]
npm的源已经是1.1.23了，你可能用的是taobao的源

**Comment by ganisback** [comment]
@monkeydbobo , thanks, you save my life
