### ISSUE TITLE
安卓如何关闭推送

### ISSUE THREAD

**Issue by ciuji** [GetuiLaboratory/react-native-getui#19]
使用getuimodule里面的stop方法吗？可是尝试过各种方法，status显示的状态仍然是1，仍在运行。
所以应该如何实现关闭推送呢。谢谢。

**Comment by ciuji** [comment]
destory()之后使用status方法，返回的仍然是1，这时候推送功能还有吗？谢谢。

**Comment by GetuiLab** [comment]
您好：
  针对您反馈的问题，可加官网技术支持QQ 具体沟通协助您排查解决。


support@getui.com
 
发件人： ciuji
发送时间： 2018-05-16 14:19
收件人： GetuiLaboratory/react-native-getui
抄送： Subscribed
主题： [GetuiLaboratory/react-native-getui] 安卓如何关闭推送 (#19)
使用getuimodule里面的stop方法吗？可是尝试过各种方法，status显示的状态仍然是1，仍在运行。
所以应该如何实现关闭推送呢。谢谢。

**Comment by GetuiLab** [comment]
您好：
  针对您反馈的问题，可加官网技术支持QQ 具体沟通协助您排查解决。



support@getui.com
 
发件人： ciuji
发送时间： 2018-05-16 15:09
收件人： GetuiLaboratory/react-native-getui
抄送： Subscribed
主题： Re: [GetuiLaboratory/react-native-getui] 安卓如何关闭推送 (#19)
destory()之后使用status方法，返回的仍然是1，这时候推送功能还有吗？谢谢。
―

**Comment by monkeydbobo** [comment]
你调用了Getui.destroy的方法，client就是offline了，就收不到推送了，你再去调用resume方法，设备就在线了，可以收到推送了。你可以自己试一下

**Comment by GetuiLab** [comment]
您好：
  针对您反馈的问题，可加官网技术支持QQ 具体沟通协助您排查解决。


support@getui.com
 
发件人： wanghaobo
发送时间： 2018-05-16 16:57
收件人： GetuiLaboratory/react-native-getui
抄送： GetuiLab; Comment
主题： Re: [GetuiLaboratory/react-native-getui] 安卓如何关闭推送 (#19)
你调用了Getui.destroy的方法，client就是offline了，就收不到推送了，你再去调用resume方法，设备就在线了，可以收到推送了。你可以自己试一下
