### ISSUE TITLE
老哥  typeError: expended dynamic type 'boolean', but had type 'string' (constructiong arguments for GetuiModule.runBackgroundEnable at argument index 0)

### ISSUE THREAD

**Issue by showtan001** [GetuiLaboratory/react-native-getui#20]
typeError: expended dynamic type 'boolean', but had type 'string' (constructiong arguments for GetuiModule.runBackgroundEnable at argument index 0)
 rn 0.51.0
getui  最新版本

**Comment by Ezreal-lup** [comment]
please use  "Getui.runBackgroundEnable(true); "
