### ISSUE TITLE
ios透传消息，payload参数不能获取到

### ISSUE THREAD

**Issue by dzeze** [GetuiLaboratory/react-native-getui#22]
你好，请问下ios app在线时收到透传消息，怎么做到在顶部显示呢，这时候payload参数也不能获取到。

**Comment by tomorrowNicest** [comment]
大佬，我按照配置，在ios端接收不到消息诶，ios端配置有什么需要注意的吗？

**Comment by dzeze** [comment]
ios端消息透传的，而且需要在xcode 中打开配送推送
