### ISSUE TITLE
这个插件能获取cid嘛

### ISSUE THREAD

**Issue by tomorrowNicest** [GetuiLaboratory/react-native-getui#25]
![qq 20180801193440](https://user-images.githubusercontent.com/34731610/43519438-0a59d020-95c2-11e8-9667-0e41c065e87e.png)

**Comment by roy2651** [comment]
兄弟，clientID为空怎么解决的你

**Comment by monkeydbobo** [comment]
参照pushDemo_new工程

**Comment by GetuiLab** [comment]
可以获取到的，如果还有疑问，麻烦加下官网首页技术支持的qq。



support@getui.com
 
发件人： wanghaobo
发送时间： 2019-02-12 17:13
收件人： GetuiLaboratory/react-native-getui
抄送： Subscribed
主题： Re: [GetuiLaboratory/react-native-getui] 这个插件能获取cid嘛 (#25)
参照pushDemo_new工程

**Comment by GetuiLab** [comment]
麻烦加下官网首页技术支持的qq沟通您的问题！



support@getui.com
 
发件人： 韩加华
发送时间： 2019-02-12 17:09
收件人： GetuiLaboratory/react-native-getui
抄送： Subscribed
主题： Re: [GetuiLaboratory/react-native-getui] 这个插件能获取cid嘛 (#25)
兄弟，clientID为空怎么解决的你
