### ISSUE TITLE
升级rn到0.56.0后编译报错

### ISSUE THREAD

**Issue by YanyunHuang** [GetuiLaboratory/react-native-getui#27]
最近将 react native 升级到了0.56.0 版本，结果报错： error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'  。

**Comment by roubo** [comment]
同样遇到了，as下编译会报错，react-native run android 没问题。

**Comment by VictorYuan666** [comment]
好像更导入方式有关系以前是compile 现在是implementation project(':react-native-getui') 官方解决下啊 很头疼

**Comment by 452MJ** [comment]
implementation换成api 试试，再不行直接用回compile
