### ISSUE TITLE
Android依赖的个推SDK名称为什么都是google-play结尾的？

### ISSUE THREAD

**Issue by zhangxy1219** [GetuiLaboratory/react-native-getui#29]
我们的Android应用不需要上架Google Play Store，也能用这些的SDK么？

**Comment by GetuiLab** [comment]
您好，不是海外推送的，您选择圈出来的部分下载就可以了！








support@getui.com
 
发件人： zhangxy1219
发送时间： 2018-11-08 19:29
收件人： GetuiLaboratory/react-native-getui
抄送： Subscribed
主题： [GetuiLaboratory/react-native-getui] Android依赖的个推SDK名称为什么都是google-play结尾的？ (#29)
我们的Android应用不需要上架Google Play Store，也能用这些的SDK么？

**Comment by zhangxy1219** [comment]
@GetuiLab “圈出来的部分下载”具体是什么意思啊？现在react-native-getui的android/build.gradle里面强制依赖了google-play版本的sdk，https://github.com/GetuiLaboratory/react-native-getui/blob/master/android/build.gradle#L62-L65，请问需要怎么修改才能依赖非google-play版本的sdk？

**Comment by GetuiLab** [comment]
麻烦加官网首页技术支持的qq，详细沟通您的问题！


support@getui.com
 
发件人： zhangxy1219
发送时间： 2018-11-09 11:41
收件人： GetuiLaboratory/react-native-getui
抄送： GetuiLab; Mention
主题： Re: [GetuiLaboratory/react-native-getui] Android依赖的个推SDK名称为什么都是google-play结尾的？ (#29)
@GetuiLab “圈出来的部分下载”具体是什么意思啊？现在react-native-getui的android/build.gradle里面强制依赖了google-play版本的sdk，https://github.com/GetuiLaboratory/react-native-getui/blob/master/android/build.gradle#L62-L65，请问需要怎么修改才能依赖非google-play版本的sdk？
