### ISSUE TITLE
升级到xcode10之后，iOS release包 crash。

### ISSUE THREAD

**Issue by XinQiXiao** [GetuiLaboratory/react-native-getui#30]
项目环境：
    react-native: 0.50.4
    react: 16.0.0
    react-native-getui: 1.1.7

问题：升级到xcode10之后，打release包，安装到iPHone手机上，每天前几次运行会crash。

**Comment by XinQiXiao** [comment]
可能导致问题原因，Xcode10 建议开启Wifi信息授权

解决如下：
        并没有升级本地个推版本，按照个推官网，http://docs.getui.com/getui/mobile/ios/xcode/  中3.7条
Xcode10 建议开启Wifi信息授权，操作配置。再打包发现问题不复现。

后续：
        wifi信息授权的开启，为何会导致这个原因呢？

**Comment by GetuiLab** [comment]
您好，麻烦加下官网首页技术支持的qq，提供下具体的奔溃日志。



support@getui.com
 
发件人： Ezreal-lup
发送时间： 2019-04-08 09:55
收件人： GetuiLaboratory/react-native-getui
抄送： Subscribed
主题： Re: [GetuiLaboratory/react-native-getui] 升级到xcode10之后，iOS release包 crash。 (#30)
Reopened #30.
