### ISSUE TITLE
ERROR: Failed to resolve: com.getui:hwp-for-google-play:1.0.4

### ISSUE THREAD

**Issue by L-x-C** [GetuiLaboratory/react-native-getui#31]
安卓用android studio跑不起来，会报
![image](https://user-images.githubusercontent.com/4329120/54348192-7dfe7900-4683-11e9-9641-65c4407c141a.png)

**Comment by L-x-C** [comment]
重启了下android studio好了...

**Comment by monkeydbobo** [comment]
https://github.com/GetuiLaboratory/react-native-getui/tree/master/example/RN%E5%A4%9A%E5%8E%82%E5%95%86 
如果想使用多厂商版本请参考以上文档
如果不使用多厂商版本请用1.1.25版本

**Comment by GetuiLab** [comment]
好的，之后有问题继续沟通，感谢您的反馈！



support@getui.com
 
From: L-x-C
Date: 2019-03-14 18:03
To: GetuiLaboratory/react-native-getui
CC: Subscribed
Subject: [GetuiLaboratory/react-native-getui] ERROR: Failed to resolve: com.getui:hwp-for-google-play:1.0.4 (#31)
安卓用android studio跑不起来，会报

**Comment by houdzaiw** [comment]
Could not find com.getui:hwp-for-google-play:1.0.4.
Required by:
    project :app > project :react-native-getui
Search in build.gradle files
我也遇到同样的问题，请问怎么解决的，谢谢

**Comment by monkeydbobo** [comment]
https://github.com/GetuiLaboratory/react-native-getui/tree/master/example/RN%E5%A4%9A%E5%8E%82%E5%95%86
如果想使用多厂商版本请参考以上文档
如果不使用多厂商版本请用1.1.25版本
