### ISSUE TITLE
模拟器能收到消息，但是真机收不到消息

### ISSUE THREAD

**Issue by 2534290808** [GetuiLaboratory/react-native-getui#32]
模拟器调试能收到消息，但是真机调试收不到消息

**Comment by monkeydbobo** [comment]
请问下你的手机是哪个Android哪个版本的，注意一下手机推送所需要的权限

**Comment by 2534290808** [comment]
我的手机是android 9.0的，已经确定权限已经打开了

**Comment by GetuiLab** [comment]
您好，麻烦加下官网首页技术支持的qq，提供一下具体收不到的clientid和taskid，我们具体排查一下！



support@getui.com
 
发件人： 黎明
发送时间： 2019-04-07 22:34
收件人： GetuiLaboratory/react-native-getui
抄送： Subscribed
主题： [GetuiLaboratory/react-native-getui] 模拟器能收到消息，但是真机收不到消息 (#32)

**Comment by monkeydbobo** [comment]
Android9.0需要在 android/app/src/main/AndroidManifest.xml <application/>节点中添加
android:useCleartextTraffic="true"

**Comment by 2534290808** [comment]
好的，我试试

**Comment by 2534290808** [comment]
可以接受了，感谢您的耐心解答
