### ISSUE TITLE
请更新编译版本依赖方式

### ISSUE THREAD

**Issue by tututututututu** [GetuiLaboratory/react-native-getui#33]
作为一个三方库，应该使用如下这种方式来制定编译版本及工具版本，而不是写死

def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion safeExtGet('compileSdkVersion', 26)
    buildToolsVersion safeExtGet('buildToolsVersion', '26.0.3')

    defaultConfig {
        consumerProguardFiles 'proguard-rules.pro'
    }

    defaultConfig {
        minSdkVersion safeExtGet('minSdkVersion', 16)
        targetSdkVersion safeExtGet('targetSdkVersion', 26)
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    lintOptions {
       warning 'InvalidPackage'
    }
}

dependencies {
    compile 'com.facebook.react:react-native:+'
    compile 'io.sentry:sentry-android:1.7.5'
}

**Comment by monkeydbobo** [comment]
Thanks for your advice, we will fix it at next version
