### ISSUE TITLE
绑定别名推送失败

### ISSUE THREAD

**Issue by 2534290808** [GetuiLaboratory/react-native-getui#35]
绑定别名推送失败

**Comment by GetuiLab** [comment]
绑定别名失败，具体返回什么错误信息，麻烦加下官网首页技术支持的qq，提供详细的信息，排查问题！



support@getui.com
 
发件人： 黎明
发送时间： 2019-04-20 19:36
收件人： GetuiLaboratory/react-native-getui
抄送： Subscribed
主题： [GetuiLaboratory/react-native-getui] 绑定别名推送失败 (#35)
绑定别名推送失败

**Comment by 2534290808** [comment]
我手机端绑定别名，然后服务器端使用别名进行推送，提示别名没有绑定，但是我极端确实执行绑定别名的方法

**Comment by GetuiLab** [comment]
麻烦加官网首页技术支持的qq




support@getui.com
 
发件人： 黎明
发送时间： 2019-04-22 14:07
收件人： GetuiLaboratory/react-native-getui
抄送： GetuiLab; Comment
主题： Re: [GetuiLaboratory/react-native-getui] 绑定别名推送失败 (#35)
我手机端绑定别名，然后服务器端使用别名进行推送，提示别名没有绑定，但是我极端确实执行绑定别名的方法

**Comment by 2534290808** [comment]
已经解决，谢谢

**Comment by GetuiLab** [comment]
不客气



support@getui.com
 
发件人： 黎明
发送时间： 2019-04-22 22:15
收件人： GetuiLaboratory/react-native-getui
抄送： GetuiLab; Comment
主题： Re: [GetuiLaboratory/react-native-getui] 绑定别名推送失败 (#35)
已经解决，谢谢

**Comment by 289420843** [comment]
具体怎么解决的？ 我也遇到相同的问题

**Comment by Ezreal-lup** [comment]
Getui.bindAlias('www','111');参数可以根据你自己的需求去填写，然后提供cid和AppID可以给我们的技术支持，看看是否绑定成功
