### ISSUE TITLE
android - Is there a way to continue to receive notifications after app is killed?

### ISSUE THREAD

**Issue by chilidoggca** [GetuiLaboratory/react-native-getui#37]
In my emulator, I can continue to receive notifications after closing my app. However, on a real android device (9.0), I can only receive notifications if the app is open or running in background. **If the app is closed, no notifications are received.**

I am only using this library for my android builds.

React native 0.55.3, react-native-getui 1.1.25
I had followed the steps in the documentation.

**Comment by monkeydbobo** [comment]
Service would be killed when you switch it to background  in 1 min, on Android  Pie device(9.0). Now you can keep service running by reducing your targetSDK(< 26). We will fix the problem next version.

**Comment by chilidoggca** [comment]
Thanks for the response. Would target sdk 26 work in the meantime?

**Comment by monkeydbobo** [comment]
less  than 26

**Comment by chilidoggca** [comment]
Thank you. Unfortunately, going to lower target sdk would not work for us because Google Play Store requires minimum 28 target sdk. When can we expect the next version?

I will likely have to try a different service because we need this feature to work urgently.

**Comment by chilidoggca** [comment]
Just an update to say I ended up using FCM for phones with google play services installed and this library for other android phones. Thanks for all the great work!
