### ISSUE TITLE
个推真机获取不到cid

### ISSUE THREAD

**Issue by bocaiJs** [GetuiLaboratory/react-native-getui#42]
再ios的模拟器和android的模拟器都是可以获取到cid的

再android真机调试的时候就获取不到cid
调试模式提示会缺少一个文件
![image](https://user-images.githubusercontent.com/19830233/57312854-f2541680-7120-11e9-9e43-63adf6e93bcc.png)
app打正式包后不会提示缺少文件
但是依然获取不到cid.

请问是什么原因呢
```
 Getui.clientId((param)=> {
            alert(param);
            this.props.dispatch(login_done({getui_cid:param}))
        })
```

**Comment by bocaiJs** [comment]
@monkeydbobo  大佬 能帮我瞅一眼嘛

**Comment by monkeydbobo** [comment]
你用的是哪个版本的react-native-getui

**Comment by bocaiJs** [comment]
@monkeydbobo    "react-native-getui": "1.1.25", 官网推荐的这个版本

**Comment by monkeydbobo** [comment]
检查一下node_modules/react-native-getui/android/src/main/jniLibs目录下的so包是否为libgetuiext3.so

**Comment by monkeydbobo** [comment]
在android/app/build.gradle里面加上defaultConfig字段里面加上
`  ndk {
            abiFilters "armeabi-v7a", "x86"
        }`

**Comment by bocaiJs** [comment]
@monkeydbobo 可以了 老哥 感谢你

**Comment by lavender21** [comment]
我也遇到同样的问题，node_modules/react-native-getui/android/src/main/jniLibs包含两个文件夹armeabi-v7a 和 x86 底下分别包含了libgetuiext3.so， android/app/build.gradle里面也加上了 `ndk { abiFilters "armeabi-v7a", "x86" }` 依旧还有这个问题

**Comment by monkeydbobo** [comment]
可能你的设备是armebi架构的。 多加一个so加载项。ndk { abiFilters "armeabi","armeabi-v7a", "x86" }
