### ISSUE TITLE
org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.getui:hwp-for-google-play:1.0.4.

### ISSUE THREAD

**Issue by puxiaoshuai** [GetuiLaboratory/react-native-getui#44]
org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.getui:hwp-for-google-play:1.0.4.,运行报错

**Comment by monkeydbobo** [comment]
用AndroidStudio打开project/android工程 重新构建一下
