### ISSUE TITLE
海外推送

### ISSUE THREAD

**Issue by mingxin-yang** [GetuiLaboratory/react-native-getui#45]
需要支持海外推送，不需要多厂商，应该怎么集成

**Comment by monkeydbobo** [comment]
我记得海外推送有一个叫react-native-notification的，可以用fcm

**Comment by mingxin-yang** [comment]
@monkeydbobo 使用 react-native-push-notification，应用被杀掉之后，就收不到通知了，不知道是不是国内手机的Google play service被阉割了
