### ISSUE TITLE
透传消息收到后，notificationClicked事件无法获取到notification的信息

### ISSUE THREAD

**Issue by L-x-C** [GetuiLaboratory/react-native-getui#46]
![image](https://user-images.githubusercontent.com/4329120/63329772-24525700-c365-11e9-85c1-dfa4b9055621.png)

我们在做收到推送，点击跳转到对应页面中，但notificationClicked事件中没有获取到推送的信息，所以无法知道该往哪跳了
payload里有信息

**Comment by GetuiLab** [comment]
notificationClicked事件无法获取自定义的内容，自定义的数据会有对应的方法获取，如果还有疑问，马上加下官网首页技术支持的qq详细沟通您的问题！



support@getui.com
 
发件人： L-x-C
发送时间： 2019-08-20 16:12
收件人： GetuiLaboratory/react-native-getui
抄送： Subscribed
主题： [GetuiLaboratory/react-native-getui] 透传消息收到后，notificationClicked事件无法获取到notification的信息 (#46)
我们在做收到推送，点击跳转到对应页面中，但notificationClicked事件中没有获取到推送的信息，所以无法知道该往哪跳了
payload里有信息

**Comment by L-x-C** [comment]
> notificationClicked事件无法获取自定义的内容，自定义的数据会有对应的方法获取，如果还有疑问，马上加下官网首页技术支持的qq详细沟通您的问题！ support@getui.com 发件人： L-x-C 发送时间： 2019-08-20 16:12 收件人： GetuiLaboratory/react-native-getui 抄送： Subscribed 主题： [GetuiLaboratory/react-native-getui] 透传消息收到后，notificationClicked事件无法获取到notification的信息 (#46) 我们在做收到推送，点击跳转到对应页面中，但notificationClicked事件中没有获取到推送的信息，所以无法知道该往哪跳了 payload里有信息 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

请问是什么方法？有相关的文档吗，我之前加过QQ，QQ群里问了没理我。
能直接给个文档我自己看也可以，感谢！

**Comment by Ezreal-lup** [comment]
var clickRemoteNotificationSub = NativeAppEventEmitter.addListener(
    'clickRemoteNotification',
    (notification) => {
        Alert.alert('点击通知',JSON.stringify(notification))
    }
);
这个是监听点击通知的事件

**Comment by L-x-C** [comment]
> var clickRemoteNotificationSub = NativeAppEventEmitter.addListener(
> 'clickRemoteNotification',
> (notification) => {
> Alert.alert('点击通知',JSON.stringify(notification))
> }
> );
> 这个是监听点击通知的事件

这个我也试过，没触发这个，只触发了notificationClicked，你那边能触发这个吗？

**Comment by Ezreal-lup** [comment]
我这边刚才真机测试了一下，是可以的，你这样修改，你在监听receiveRemoteNotification的时候不要监听notificationClick和notificationArrived,单独在后面监听点击通知的方法，就是我上面给你说的那个方法。

**Comment by L-x-C** [comment]
> 我这边刚才真机测试了一下，是可以的，你这样修改，你在监听receiveRemoteNotification的时候不要监听notificationClick和notificationArrived,单独在后面监听点击通知的方法，就是我上面给你说的那个方法。

试了，我把receiveRemoteNotification的完全删了，只留了clickRemoteNotification部分，也没执行。点击后只能唤起app，但没有任何的alert或者console
原生里要加东西吗？应该不用吧，而且我是安卓直接连usb的debug包有关系吗

**Comment by monkeydbobo** [comment]
notificationClicked 本来就跟透传消息没有关系的，只是通知消息的

**Comment by L-x-C** [comment]
感谢大家的帮助，我知道了，原生里自己加了事件传给rn就好了
