### ISSUE TITLE
今天刚更新完react，然后 react-native link 就报错了，之前的是可以的

### ISSUE THREAD

**Issue by py3613778** [GetuiLaboratory/react-native-getui#5]
终端 提示 Command `link` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project.
但是项目里面已经 npm install了，而且之前弄过demo，是可以的，不知道为什么，今天就不行了

**Comment by recwert** [comment]
@py3613778 react-native link 命令是react-native的命令，跟插件无关的。你需要确保你调用react-native link命令是在你的项目根目录下调用的。

**Comment by py3613778** [comment]
是的，很确定在项目的根目录调用，只不过不知道和升级是否有关系

**Comment by recwert** [comment]
如果觉得和升级插件有关，可以尝试回退版本后，再使用react-native link 命令，如果还是一样的错误，应该就是就和插件升级无关了。
