### ISSUE TITLE
pod 依赖错误

### ISSUE THREAD

**Issue by tututututututu** [GetuiLaboratory/react-native-getui#55]
IOS平台
GtSdkRN.podspec 指定了   s.ios.deployment_target = '7.0'
又在GeTuiSdk.h 代码里面检测
#if __IPHONE_OS_VERSION_MIN_REQUIRED < 80000
#error "GeTuiSDK is requested iOS8 or iOS8 above version"
#endif

你们自己使用pod依赖测试过吗

**Comment by Ezreal-lup** [comment]
这个已经修改过了！

**Comment by Ezreal-lup** [comment]
周一已经提交上去了，你那边可以重新拉一下最新的包试试

**Comment by tututututututu** [comment]
https://registry.npmjs.org/react-native-getui/-/react-native-getui-1.1.32.tgz
你下载试试,提交到哪个源去了

**Comment by Ezreal-lup** [comment]
我们肯定是提交到官网源
<img width="391" alt="image" src="https://user-images.githubusercontent.com/40780223/67359416-c248e480-f595-11e9-9b58-6b9e4b22c77b.png">
我这边自己操作了，下载下来了，版本是1.1.34
你看看你那边是不是用的淘宝源
