### ISSUE TITLE
关于多厂商推送的一些问题？？

### ISSUE THREAD

**Issue by xxj95719** [GetuiLaboratory/react-native-getui#59]
问题1:多厂商推送应该可以在杀死进程情况下，收到消息吧？
问题2:个推后台配置了多厂商的参数与及项目里也加了参数，杀死进程没有收到消息？
![image](https://user-images.githubusercontent.com/27256120/75091115-dda81880-55a4-11ea-83e7-4e783563bcec.png)
![image](https://user-images.githubusercontent.com/27256120/75091122-f0bae880-55a4-11ea-922d-b825212a285a.png)
![image](https://user-images.githubusercontent.com/27256120/75091136-06c8a900-55a5-11ea-97f0-6551bcafa9c9.png)

**Comment by xxj95719** [comment]
已解决

**Comment by coolRoger** [comment]
@asasugar 请问怎么解决？
