### ISSUE TITLE
急 RN0.47版本无法使用个推

### ISSUE THREAD

**Issue by RaySaii** [GetuiLaboratory/react-native-getui#8]
RN0.47 removed unused registration of JS modules
![image](https://user-images.githubusercontent.com/24506255/29957113-46ca0878-8f1e-11e7-98bc-cbef812d2654.png)
0.47版本无法使用个推

**Comment by recwert** [comment]
是的，0.47版本中的ReactPackage移除了createJSModules方法。您可以先尝试在node_module中找到个推模块，然后找到GetuiPackage，去除createJSModules方法上的@Override注解。后续我们会去除这个注解。

**Comment by GetuiLab** [comment]
麻烦加下官网技术支持的qq，这样沟通比较方便。



support@getui.com
 
发件人： RaySaii
发送时间： 2017-09-01 14:04
收件人： GetuiLaboratory/react-native-getui
抄送： Subscribed
主题： [GetuiLaboratory/react-native-getui] 急 RN0.47版本无法使用个推 (#8)
RN0.47 removed unused registration of JS modules

0.47版本无法使用个推

**Comment by recwert** [comment]
已经更新插件版本到 1.1.18，适配了rn 0.47
