### ISSUE TITLE
SDK 存在读取用户隐私的行为

### ISSUE THREAD

**Issue by kangfenmao** [GetuiLaboratory/react-native-getui#83]
## 应用商店审核结果

![image](https://user-images.githubusercontent.com/8253512/126762433-fbbb53f9-8734-4c66-ae6e-0fa5ffc08f73.png)

## 日志

获取应用列表
发生时间 2021-07-22 20:11:43 md5=0CD4B9616582AB42B922E06FEF0BB52B,pkg=com.xxx.xxx,action=android.permission.MY_READ_INSTALLED_PACKAGES,content=xxxx(com.xxx.xxx);,callstack:android.app.ApplicationPackageManager.getInstalledPackages:833;com.meizu.cloud.pushsdk.util.MzSystemUtils.getInstalledPackage:12;com.meizu.cloud.pushsdk.a.c.d:49;com.meizu.cloud.pushsdk.a.c.a:12;com.meizu.cloud.pushsdk.a.c.<init>:44;com.meizu.cloud.pushsdk.a.c.<init>:0;com.meizu.cloud.pushsdk.a.c$a.a:3;com.meizu.cloud.pushsdk.a.a.c:9;com.meizu.cloud.pushsdk.a.a.a:5;com.meizu.cloud.pushsdk.a.a$1.run:2;
获取应用列表
发生时间 2021-07-22 20:12:31 md5=0CD4B9616582AB42B922E06FEF0BB52B,pkg=com.xxx.xxx,action=android.permission.MY_READ_INSTALLED_PACKAGES,content=xxx(com.xxx.xxx);,callstack:android.app.ApplicationPackageManager.getInstalledPackages:833;com.meizu.cloud.pushsdk.util.MzSystemUtils.getInstalledPackage:12;com.meizu.cloud.pushsdk.a.c.d:49;com.meizu.cloud.pushsdk.a.c.a:12;com.meizu.cloud.pushsdk.a.c.<init>:44;com.meizu.cloud.pushsdk.a.c.<init>:0;com.meizu.cloud.pushsdk.a.c$a.a:3;com.meizu.cloud.pushsdk.a.a.c:9;com.meizu.cloud.pushsdk.a.a.a:5;com.meizu.cloud.pushsdk.a.a$1.run:2;

## 问题总结

魅族SDK会读取用户应用列表

**Comment by kangfenmao** [comment]
_reactNativeGetui.default.initSdk is not a function

**Comment by kangfenmao** [comment]
希望能够使用 js 来调用 initSdk 函数，实际上调用会报错

_reactNativeGetui.default.initSdk is not a function

**Comment by samuelchanchan** [comment]
@kangfenmao 解決了嗎?

**Comment by kangfenmao** [comment]
> @kangfenmao 解決了嗎?

解决了

[react-native-getui.zip](https://github.com/GetuiLaboratory/react-native-getui/files/6991821/react-native-getui.zip)
